### ISSUE TITLE
No module named 'data.dna_rendering'

### ISSUE THREAD

**Issue by yejr0229** [skhu101/GauHuman#1]
After set the environment,I run this script "bash run_zju_mocap_refine.sh",and encounter:
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    from gaussian_renderer import render, network_gui
  File "/home/yejr/Digital_Avater/GauHuman-main/gaussian_renderer/__init__.py", line 15, in <module>
    from scene.gaussian_model import GaussianModel
  File "/home/yejr/Digital_Avater/GauHuman-main/scene/__init__.py", line 16, in <module>
    from scene.dataset_readers import sceneLoadTypeCallbacks
  File "/home/yejr/Digital_Avater/GauHuman-main/scene/dataset_readers.py", line 33, in <module>
    from data.dna_rendering.dna_rendering_sample_code.SMCReader import SMCReader
ModuleNotFoundError: No module named 'data.dna_rendering'
How to deal with it?

**Comment by skhu101** [comment]
Hi, thanks for your interest in our work. The missing file has been added.

**Comment by yejr0229** [comment]
Thanks for replying,and I have another problem.
Now I use my_377 to train,and encounter:
  File "train.py", line 45, in training
    scene = Scene(dataset, gaussians)
  File "/home/yejr/Digital_Avater/GauHuman-main/scene/__init__.py", line 60, in __init__
    assert False, "Could not recognize scene type!"
AssertionError: Could not recognize scene type!
 And I check the dataset thar put in Scene(),it is like:
dataset
<arguments.GroupParams object at 0x7f5636fe02b0>
special variables
actor_gender:'neutral'
data_device:'cuda'
eval:True
exp_name:'zju_mocap_refine/debug'
images:'images'
model_path:'/media/data4/yejr/GauHuman/output/zju_mocap_refine/debug'
motion_offset_flag:True
resolution:-1
sh_degree:3
smpl_type:'smpl'
source_path:'/media/data4/yejr/refined_ZJU_MoCap_instant_nvr/my_377'
white_background:False
How should I do?

**Comment by skhu101** [comment]
Hi, we have an if judgment sentence in line 50 of scene/__init__.py. You can modify the dataset name to zju_mocap_refine in your data directory or change the judgment sentence.

**Comment by yejr0229** [comment]
Thanks for replying,and I encounter another problem now.I run this command "CUDA_VISIBLE_DEVICES=1 bash train_zju_mocap_refine.sh" with no answer:
^CTraceback (most recent call last):
  File "train.py", line 16, in <module>
    from gaussian_renderer import render, network_gui
  File "/home/yejr/Digital_Avater/GauHuman-main/gaussian_renderer/__init__.py", line 15, in <module>
    from scene.gaussian_model import GaussianModel
  File "/home/yejr/Digital_Avater/GauHuman-main/scene/__init__.py", line 16, in <module>
    from scene.dataset_readers import sceneLoadTypeCallbacks
  File "/home/yejr/Digital_Avater/GauHuman-main/scene/dataset_readers.py", line 28, in <module>
    from scene.gaussian_model import BasicPointCloud
  File "/home/yejr/Digital_Avater/GauHuman-main/scene/gaussian_model.py", line 23, in <module>
    from knn_cuda import KNN
  File "/media/data4/yejr/conda_env/gauhuman/lib/python3.8/site-packages/knn_cuda/__init__.py", line 38, in <module>
    _knn = load_cpp_ext("knn")
  File "/media/data4/yejr/conda_env/gauhuman/lib/python3.8/site-packages/knn_cuda/__init__.py", line 26, in load_cpp_ext
    ext = load(
  File "/media/data4/yejr/conda_env/gauhuman/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/media/data4/yejr/conda_env/gauhuman/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1523, in _jit_compile
    baton.wait()
  File "/media/data4/yejr/conda_env/gauhuman/lib/python3.8/site-packages/torch/utils/file_baton.py", line 42, in wait
    time.sleep(self.wait_seconds)
KeyboardInterrupt
How should I do?
