### ISSUE TITLE
Failed to train with error: Command '['ninja', '-v']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by Whitepainter** [skhu101/GauHuman#11]
Hi,
I met a problem when "bash train_zju_mocap_refine.sh". The combination is gcc12.3+cuda11.8+ninja1.10.2.4+pytorch2.0.0.

The error information is as follows：
Traceback (most recent call last):
  File "C:\Users\Mr.Lin\anaconda3\envs\gauhuman\lib\site-packages\torch\utils\cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "C:\Users\Mr.Lin\anaconda3\envs\gauhuman\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 16, in <module>
    from gaussian_renderer import render, network_gui
  File "C:\Users\Mr.Lin\Desktop\PROJECT\gauhuman\gaussian_renderer\__init__.py", line 15, in <module>
    from scene.gaussian_model import GaussianModel
  File "C:\Users\Mr.Lin\Desktop\PROJECT\gauhuman\scene\__init__.py", line 16, in <module>
    from scene.dataset_readers import sceneLoadTypeCallbacks
  File "C:\Users\Mr.Lin\Desktop\PROJECT\gauhuman\scene\dataset_readers.py", line 28, in <module>
    from scene.gaussian_model import BasicPointCloud
  File "C:\Users\Mr.Lin\Desktop\PROJECT\gauhuman\scene\gaussian_model.py", line 23, in <module>
    from knn_cuda import KNN
  File "C:\Users\Mr.Lin\anaconda3\envs\gauhuman\lib\site-packages\knn_cuda\__init__.py", line 38, in <module>
    _knn = load_cpp_ext("knn")
  File "C:\Users\Mr.Lin\anaconda3\envs\gauhuman\lib\site-packages\knn_cuda\__init__.py", line 26, in load_cpp_ext
    ext = load(
  File "C:\Users\Mr.Lin\anaconda3\envs\gauhuman\lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "C:\Users\Mr.Lin\anaconda3\envs\gauhuman\lib\site-packages\torch\utils\cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\Mr.Lin\anaconda3\envs\gauhuman\lib\site-packages\torch\utils\cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "C:\Users\Mr.Lin\anaconda3\envs\gauhuman\lib\site-packages\torch\utils\cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'knn': [1/1] "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64/link.exe" knn.o knn.cuda.o /nologo /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:C:\Users\Mr.Lin\anaconda3\envs\gauhuman\lib\site-packages\torch\lib torch_python.lib /LIBPATH:C:\Users\Mr.Lin\anaconda3\envs\gauhuman\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" cudart.lib /out:knn.pyd
FAILED: knn.pyd
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64/link.exe" knn.o knn.cuda.o /nologo /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:C:\Users\Mr.Lin\anaconda3\envs\gauhuman\lib\site-packages\torch\lib torch_python.lib /LIBPATH:C:\Users\Mr.Lin\anaconda3\envs\gauhuman\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" cudart.lib /out:knn.pyd
   Creating library knn.lib and object knn.exp
knn.o : error LNK2019: unresolved external symbol "public: long * __cdecl at::TensorBase::data_ptr<long>(void)const " (??$data_ptr@J@TensorBase@at@@QEBAPEAJXZ) referenced in function "public: long * __cdecl at::Tensor::data<long>(void)const " (??$data@J@Tensor@at@@QEBAPEAJXZ)
knn.pyd : fatal error LNK1120: 1 unresolved externals
ninja: build stopped: subcommand failed.

**Comment by Whitepainter** [comment]
edit the D:\Anaconda\envs\torch1.8.2\lib\site-packages\torch\utils\cpp_extension.py"

change the '['ninja', '-v']' in cpp_extension.py to '['ninja', '--version']', this problem will be solved.

**Comment by cyhhhhhhit** [comment]
hi，after that, i faced a new problem, knn.so not found. Do you have any solution about that?
