### ISSUE TITLE
ImportError: DLL load failed while importing knn

### ISSUE THREAD

**Issue by Whitepainter** [skhu101/GauHuman#12]
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    from gaussian_renderer import render, network_gui
  File "C:\Users\Mr.Lin\Desktop\PROJECT\gauhuman\gaussian_renderer\__init__.py", line 15, in <module>
    from scene.gaussian_model import GaussianModel
  File "C:\Users\Mr.Lin\Desktop\PROJECT\gauhuman\scene\__init__.py", line 16, in <module>
    from scene.dataset_readers import sceneLoadTypeCallbacks
  File "C:\Users\Mr.Lin\Desktop\PROJECT\gauhuman\scene\dataset_readers.py", line 28, in <module>
    from scene.gaussian_model import BasicPointCloud
  File "C:\Users\Mr.Lin\Desktop\PROJECT\gauhuman\scene\gaussian_model.py", line 23, in <module>
    from knn_cuda import KNN
  File "C:\Users\Mr.Lin\anaconda3\envs\gauhuman\lib\site-packages\knn_cuda\__init__.py", line 38, in <module>
    _knn = load_cpp_ext("knn")
  File "C:\Users\Mr.Lin\anaconda3\envs\gauhuman\lib\site-packages\knn_cuda\__init__.py", line 26, in load_cpp_ext
    ext = load(
  File "C:\Users\Mr.Lin\anaconda3\envs\gauhuman\lib\site-packages\torch\utils\cpp_extension.py", line 1310, in load
    return _jit_compile(
  File "C:\Users\Mr.Lin\anaconda3\envs\gauhuman\lib\site-packages\torch\utils\cpp_extension.py", line 1738, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "C:\Users\Mr.Lin\anaconda3\envs\gauhuman\lib\site-packages\torch\utils\cpp_extension.py", line 2138, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: DLL load failed while importing knn: 找不到指定的模块。

**Comment by skhu101** [comment]
Hi, thanks for your interest. You can try reinstalling the cuda_knn by following our instructions.
